name: flutter_linkify
description: Turns text URLs and emails into clickable inline links in text for Flutter.
version: 5.0.2
homepage: https://github.com/Cretezy/flutter_linkify

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.13.8"

dependencies:
  flutter:
    sdk: flutter
  linkify: ^4.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  flutter_test:
    sdk: flutter
